/* Ajantis - paladin of Helm - Husam will be wary but risk it if the PC initiates */
/* Ajantis BG1NPC + BG1 Expansion */
IF
	OR(2) InParty(Myself) Global("C#HusamJoined","GLOBAL",2)
	!See([ENEMY])
	See(Player1) 
	!StateCheck(Player1,CD_STATE_NOTVALID)
	CombatCounter(0)
	GlobalLT("C#HU_SoD_OtherRomance","GLOBAL",5)
	Global("X#AjantisRomanceActive","GLOBAL",2)
	InMyArea("Ajantis")
	!Dead("Ajantis")
THEN
	RESPONSE #100
		SetGlobal("C#HU_SoD_OtherRomance","GLOBAL",5)
END