/* Dynaheir - Husam will risk it if the PC initiates */
/* Dynaheir BG1NPC */
IF
	OR(2) InParty(Myself) Global("C#HusamJoined","GLOBAL",2)
	!See([ENEMY])
	See(Player1) 
	!StateCheck(Player1,CD_STATE_NOTVALID)
	CombatCounter(0)
	GlobalLT("C#HU_SoD_OtherRomance","GLOBAL",5)
	Global("X#DynaheirRomanceActive","GLOBAL",2)
	InMyArea("Dynaheir")
	!Dead("Dynaheir")
THEN
	RESPONSE #100
		SetGlobal("C#HU_SoD_OtherRomance","GLOBAL",5)
END